version: '3'

services:

  cafe-crm:
    container_name: cafe-crm
    image: 'apbogomazov/cafe-crm:latest'
    ports:
      - '8080:8080'
    environment:
      - DB_SERVER=cafe-crm-postgres
      - POSTGRES_DB=cafe-crm
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=password
    links:
      - cafe-crm-postgres

  cafe-crm-postgres:
    container_name: postgres
    image: 'postgres:latest'
    ports:
      - '5432:5432'
    volumes:
      - cafe-crm-data:/var/lib/postgresql/data
    environment:
      - DB_SERVER=cafe-crm-postgres
      - POSTGRES_DB=cafe-crm
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=password

volumes:
  cafe-crm-data: